feat:add governance setters and minor optimizations
dougstorm/yearn-vaults-swap pull request #1
Opened 2021-02-09 21:28 UTC by dougstorm

Change Log:
* add governance setters
* add registry setter
* add sweep func
* skip dust transfers to save on gas
* add more tests to check amounts

2021-02-09 21:29 UTC, dougstorm commented on contracts/VaultSwap.sol
> -        if(balanceVaultFrom > 0) {
removing this since i added the sweep func, if there is a major issue governance can help. Also avoids sending dust and more gas cost

2021-02-09 21:30 UTC, dougstorm commented on contracts/VaultSwap.sol
> -        if(balanceToken > 0) {
same as above, tested calcs and amounts look good

2021-02-09 21:46 UTC, emilianobonassi requested changes
Thanks for the optimizations and have a governable contract.

Few optimizations need to be fixed and a test for sweep function.

Proposed some optional refactor.

2021-02-09 21:46 UTC, emilianobonassi commented on contracts/VaultSwap.sol
> -        if(balanceVaultFrom > 0) {
ok

2021-02-09 21:46 UTC, emilianobonassi commented on contracts/VaultSwap.sol
>          balanceVaultFrom = vf.balanceOf(address(this)).sub(preBalanceVaultFrom);
You could remove this line, not used.

2021-02-09 21:46 UTC, emilianobonassi commented on contracts/VaultSwap.sol
> -        if(balanceToken > 0) {
ok

2021-02-09 21:46 UTC, emilianobonassi commented on contracts/VaultSwap.sol
>          balanceToken = token.balanceOf(address(this)).sub(preBalanceToken);
You could remove this, not used.

2021-02-09 21:46 UTC, emilianobonassi commented on tests/test_trusted_swap.py
>  import pytest
You could add a test for `sweep` function, just to check the governance can withdraw

2021-02-09 21:46 UTC, emilianobonassi commented on contracts/TrustedVaultSwap.sol
> +    function acceptGovernance() external onlyPendingGovernance {
It would be a nice to have, refactor this and other governance methods/modifiers in a `Governable` mixin.

2021-02-09 21:46 UTC, emilianobonassi commented on contracts/TrustedVaultSwap.sol
> +        require(_registry != address(0), "Registry cannot be 0");
It would be a nice to have to set the require as a modifier and apply both to this method and the constructor.

2021-02-10 00:30 UTC, dougstorm commented on contracts/TrustedVaultSwap.sol
> +    function acceptGovernance() external onlyPendingGovernance {
done in latest commit

2021-02-10 00:31 UTC, dougstorm commented on tests/test_trusted_swap.py
>  import pytest
added on latest commit

2021-02-10 00:36 UTC, dougstorm commented on contracts/TrustedVaultSwap.sol
> +        require(_registry != address(0), "Registry cannot be 0");
Fair point, minor nitpicky preference, but i prefer to not have the constructor with modifiers since it already has a few extended super constructors to keep it more readable and clear on validations

2021-02-10 00:36 UTC, dougstorm commented
> Thanks for the optimizations and have a governable contract.
> 
> Few optimizations need to be fixed and a test for sweep function.
> 
> Proposed some optional refactor.

Thanks, i added most of the changes on latest commit 3950e76

2021-02-10 17:44 UTC, emilianobonassi approved these changes
LGTM

2021-02-11 13:10 UTC, merged